### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by qinghua362330** [IntelSDM/7DTD#1]
bro，thank you ，i want know how to use it ，thank you......

**Comment by IntelSDM** [comment]
> bro，thank you ，i want know how to use it ，thank you......

Add the references to the project in visual studio.
Compile the c# called 7DTD.
Navigate to the bin folder, take the 7DTD.dll, and put it in your game's base folder.
Then copy the instructions here for my other project which will allow you to bypass eac's integrity checks: https://github.com/IntelSDM/UnityStealer/blob/master/Instructions.md
Ensure the namespace, class, and function for the loader you use to initialize the cheat are the same as the one in 7DTD.
Move the 0harmony file you patched into the base folder directory as stated in the UnityStealer instructions and then it should load fine.

**Comment by worgaworga** [comment]
Can't reference UnityEngine.TextCoreModule.dll . Not in my Steam\steamapps\common\7 Days To Die\7DaysToDie_Data\Managed?
