### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Nick403** [IntelSDM/7DTD#13]
Game crashes when started with cheat, as i'm kinda new to this type of cheating, I wanna try implement a simple way to do it in assembly file, is there any way ? I would like to talk about it more on discord, could you drop the name or smt to get in contact ?

**Comment by IntelSDM** [comment]
Sorry for the late response, If it is instantly crashing I advise you to recompile the binaries from the source to use the most up-to-date DLLs from the game as reference.  If you want to make an all-in-one patching tool then you will need to use a tool like [DNLib](https://github.com/0xd4d/dnlib), It would be rather difficult and honestly not worth the time. The patching process was used to bypass EAC, this still works on Linux EAC but on Windows, it is now patched so I advise you to look into a mono injector if you want to use it on Windows.

**Comment by Nick403** [comment]
No problem, as I am at the beginning and I made the edits in the assembly...dll. I wanted to understand the full functionality and possibly learn from someone who knows and can help me with problems encountered with your "cheat" because I did not find a detailed course on this topic

**Comment by IntelSDM** [comment]
If you want to learn more about Windows and PE to understand the functionality of DLLs and dynamic linking as well as address spaces and memory management then you should pick up [Windows Internals Part 1](https://www.amazon.co.uk/Windows-Internals-Part-architecture-management/dp/0735684189)
Game hacking is a complicated topic and there is no other way to learn than jumping into the deep end. That being said 7 days to die isn't a good game to start with; It is by far one of the most poorly coded games known to man. 

That being said if you have any bugs or issues with the cheat you can just post them here with a screenshot and explanation of how it occurred and I can help.

**Comment by Nick403** [comment]
I made this code:
`using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

// Token: 0x0200164C RID: 5708
internal class AdminESP : MonoBehaviour
{
	// Token: 0x0600AAF9 RID: 43769
	public static void MYGUI()
	{
		if (GUI.Button(new Rect(20f, 20f, 130f, 30f), "SHOW/HIDE"))
		{
			AdminESP.ShowHide = !AdminESP.ShowHide;
		}
		if (AdminESP.ShowHide)
		{
			GUI.Box(new Rect(20f, 50f, 180f, 186f), "403 HACK");
			if (GUI.Button(new Rect(25f, 80f, 170f, 30f), AdminESP.string1))
			{
				AdminESP.player_esp = !AdminESP.player_esp;
			}
			if (GUI.Button(new Rect(25f, 115f, 170f, 30f), AdminESP.string2))
			{
				AdminESP.zombie_esp = !AdminESP.zombie_esp;
			}
			if (GUI.Button(new Rect(25f, 150f, 170f, 30f), AdminESP.string3))
			{
				AdminESP.player_line = !AdminESP.player_line;
			}
			if (GUI.Button(new Rect(25f, 185f, 170f, 30f), AdminESP.string4))
			{
				AdminESP.zombie_line = !AdminESP.zombie_line;
			}
		}
		if (AdminESP.player_esp)
		{
			AdminESP.string1 = "Player ESP <color=green>ON</color>";
			AdminESP.player_esp = false;
		}
		else
		{
			AdminESP.string1 = "Player ESP <color=red>OFF</color>";
			AdminESP.player_esp = true;
		}
		if (AdminESP.zombie_esp)
		{
			AdminESP.string2 = "Zombie ESP <color=green>ON</color>";
			AdminESP.zombie_esp = false;
		}
		else
		{
			AdminESP.string2 = "Zombie ESP <color=red>OFF</color>";
			AdminESP.zombie_esp = true;
		}
		if (AdminESP.player_line)
		{
			AdminESP.string3 = "Player Line <color=green>ON</color>";
			AdminESP.player_line = false;
		}
		else
		{
			AdminESP.string3 = "Player Line<color=red>OFF</color>";
			AdminESP.player_line = true;
		}
		if (AdminESP.zombie_line)
		{
			AdminESP.string4 = "Zombie Line <color=green>ON</color>";
			AdminESP.zombie_line = false;
		}
		else
		{
			AdminESP.string4 = "Zombie Line<color=red>OFF</color>";
			AdminESP.zombie_line = true;
		}
		AdminESP.Update();
		AdminESP.ESP();
	}

	// Token: 0x0600AAFA RID: 43770
	static AdminESP()
	{
		AdminESP.ShowHide = false;
		AdminESP.PlayerList = new List<EntityPlayer>();
		AdminESP.mygui = new AdminESP();
	}

	// Token: 0x0600AAFB RID: 43771
	public static void Update()
	{
		try
		{
			if (GameManager.Instance.World != null)
			{
				if (Time.time > AdminESP.CacheTime)
				{
					AdminESP.PlayerList.Clear();
					foreach (EntityPlayer entityPlayer in GameManager.Instance.World.Players.list)
					{
						if (!(entityPlayer == null) && entityPlayer.Health > 0 && entityPlayer.IsAlive())
						{
							AdminESP.PlayerList.Add(entityPlayer);
						}
					}
					AdminESP.ZombieList.Clear();
					foreach (EntityEnemy zombie in from s in UnityEngine.Object.FindObjectsOfType<EntityEnemy>()
					where s.IsAlive()
					select s)
					{
						if (!(zombie == null) && zombie.Health > 0 && zombie.IsAlive())
						{
							AdminESP.ZombieList.Add(zombie);
						}
					}
					AdminESP.CacheTime = Time.time + 3f;
				}
			}
		}
		catch (Exception arg)
		{
			Console.WriteLine("PESP LAST: {0}", arg);
		}
	}

	// Token: 0x0600AAFC RID: 43772
	public static Vector3 WorldPointToScreenPoint(Vector3 worldpoint)
	{
		Vector3 result;
		try
		{
			Vector3 vector = Camera.main.WorldToScreenPoint(worldpoint);
			vector.y = (float)Screen.height - vector.y;
			result = vector;
		}
		catch
		{
			result = new Vector3(0f, 0f, 0f);
		}
		return result;
	}

	// Token: 0x0600AAFD RID: 43773
	public static bool IsScreenPointVisible(Vector3 screenpoint)
	{
		return screenpoint.z > 0.01f && screenpoint.x > -5f && screenpoint.y > -5f && screenpoint.x < (float)Screen.width && screenpoint.y < (float)Screen.height;
	}

	// Token: 0x0600AAFF RID: 43775
	public static void ESP()
	{
		if (AdminESP.player_esp)
		{
			try
			{
				if (GameManager.Instance != null && GameManager.Instance.World != null)
				{
					try
					{
						foreach (EntityPlayer entityPlayer in AdminESP.PlayerList)
						{
							if (entityPlayer != GameManager.Instance.World.GetPrimaryPlayer() && !(entityPlayer == null) && entityPlayer.Health > 0 && entityPlayer.IsAlive())
							{
								Vector3 position = entityPlayer.transform.position;
								Vector3 vector = AdminESP.WorldPointToScreenPoint(entityPlayer.transform.position);
								Vector3 vector2 = AdminESP.WorldPointToScreenPoint(entityPlayer.emodel.GetHeadTransform().position);
								int distance = (int)Vector3.Distance(Camera.main.transform.position, entityPlayer.transform.position);
								float num = Mathf.Abs(vector2.y - vector.y);
								float num2 = num / 2f;
								string str = "(" + distance.ToString() + "m)";
								string str2 = entityPlayer.EntityName ?? "";
								string str3 = string.Format("({0})", entityPlayer.Health);
								if (AdminESP.IsScreenPointVisible(vector))
								{
									if (entityPlayer.IsAdmin || entityPlayer.IsSpectator)
									{
										Drawing.DrawString(new Vector2(vector.x, vector.y + 10f), "Admin", Color.red, true, 11, FontStyle.Normal, 3);
									}
									Render.DrawString(new Vector2(vector.x, vector.y), str2 + str + str3, Color.yellow, true, 11, FontStyle.Normal, 3);
									Render.PlayerCornerBox(new Vector2(vector2.x, vector2.y + 0.5f), num / 2f, num, 2f, distance, Color.cyan);
									Render.DrawHealthBar(entityPlayer, num, vector2.x - 0.5f, vector2.y);
									if (AdminESP.player_line)
									{
										Render.Line(new Vector2((float)(Screen.width / 2), (float)(Screen.height / 2)), new Vector2(vector2.x, vector2.y + 0.5f), Color.yellow, 1f);
									}
								}
							}
						}
					}
					catch (Exception arg)
					{
						Console.WriteLine("ERROR FIRST: {0}", arg);
					}
				}
			}
			catch (Exception arg2)
			{
				Console.WriteLine("ERROR SECOND: {0}", arg2);
			}
		}
		if (AdminESP.zombie_line)
		{
			try
			{
				if (GameManager.Instance.World != null)
				{
					foreach (EntityEnemy zombie in AdminESP.ZombieList)
					{
						if (!(zombie == null) && zombie.Health > 0 && zombie.IsAlive())
						{
							Vector3 screenposition = AdminESP.WorldPointToScreenPoint(zombie.transform.position);
							int distance2 = (int)Vector3.Distance(Camera.main.transform.position, zombie.transform.position);
							int health = zombie.Health;
							string namestr = zombie.EntityName ?? "";
							string distancestr = string.Format("({0})", zombie.Health);
							Vector3 headposition = AdminESP.WorldPointToScreenPoint(zombie.emodel.GetHeadTransform().position);
							Vector3 screenpoint = AdminESP.WorldPointToScreenPoint(zombie.transform.position);
							float height = Mathf.Abs(headposition.y - screenposition.y);
							float x = screenposition.x - height * 0.3f;
							float y = headposition.y;
							if (AdminESP.IsScreenPointVisible(screenpoint))
							{
								Drawing.DrawString(new Vector2(screenposition.x, screenposition.y), namestr + distancestr + health.ToString(), Color.red, true, 12, FontStyle.Normal, 0);
								Render.PlayerCornerBox(new Vector2(headposition.x, headposition.y + 0.5f), height / 2f, height, 2f, distance2, Color.red);
								Render.DrawHealthBar(zombie, height, x, y);
								if (AdminESP.zombie_line)
								{
									Render.Line(new Vector2((float)(Screen.width / 2), (float)(Screen.height / 2)), new Vector2(headposition.x, headposition.y + 0.5f), Color.red, 1f);
								}
							}
						}
					}
				}
			}
			catch
			{
			}
			AdminESP.MYGUI();
		}
	}

	// Token: 0x04008AAE RID: 35502
	public static AdminESP mygui;

	// Token: 0x04008AAF RID: 35503
	public static List<EntityPlayer> PlayerList;

	// Token: 0x04008AB0 RID: 35504
	private static float CacheTime;

	// Token: 0x04008AB5 RID: 35509
	public static string string1;

	// Token: 0x04008AB6 RID: 35510
	public static string string2;

	// Token: 0x04008AB7 RID: 35511
	public static string string3;

	// Token: 0x04008AB8 RID: 35512
	public static string string4;

	// Token: 0x04008AB9 RID: 35513
	public static bool ShowHide;

	// Token: 0x04008D9F RID: 36255
	public static bool player_esp;

	// Token: 0x04008DA0 RID: 36256
	public static bool zombie_esp;

	// Token: 0x04008DA1 RID: 36257
	public static bool player_line;

	// Token: 0x04008DA2 RID: 36258
	public static bool zombie_line;

	// Token: 0x04008DAB RID: 36267
	public static List<EntityEnemy> ZombieList = new List<EntityEnemy>();
}
` 
Added it as a new type in Assembly base on your code, all works but i get 3fps at best, can help me indenify the bug and fix it ? Could not find an solution for it

**Comment by Nick403** [comment]
By using your code to place the health bar next to entity:
```cs
Vector3 vector3 = AdminESP.WorldPointToScreenPoint(entityEnemy.transform.position);
Vector3 vector4 = AdminESP.WorldPointToScreenPoint(entityEnemy.emodel.GetHeadTransform().position);
float num3 = Mathf.Abs(vector4.y - vector3.y);
float x = vector3.x - num3 * 0.3f;
float y = vector4.y;
```

The helth bar is next to the entity but it is not on fixed ammount, if i change  the camera, the  X value is either in middle of entity or far away, is a fix for that ?

**Comment by albator122** [comment]
Cheat is incredible bro, it still work on linux today ? 
and i ve question which file u need to inject with a mono injector ?

**Comment by Nick403** [comment]
I made own version from it so idk of original works on linux

**Comment by IntelSDM** [comment]
The Original wont work on linux out of the box. It requires some work.
