### ISSUE TITLE
How to use in EAC protected servers

### ISSUE THREAD

**Issue by Rafa-smasher** [IntelSDM/7DTD#14]
Sorry for my lack of knowledge, but I didn't understand how to make the EAC not detect the presence of 7dtd.dll and system.dll
![image](https://github.com/IntelSDM/7DTD/assets/115306479/14aae11a-715d-457c-a180-c07f3e6a89be)

**Comment by IntelSDM** [comment]
Yeah, this bypass won't work on Windows builds of 7 days to die anymore. Most servers don't use EAC anymore but if you really want to cheat on EAC servers then replicate the process on a Linux system and it will work fine. Obviously you will need to recompile the cheat against Linux game version binaries.

**Comment by Rafa-smasher** [comment]
Can u make a single player ESP and Aimbot with EAC Bypass please?
