### ISSUE TITLE
How hijacking the Assembly works?

### ISSUE THREAD

**Issue by Nick403** [IntelSDM/7DTD#18]
This code is bing and can't really find how plagind the dll in game folder will attach it self to the assembly-csharp.dll, is there any code snippets or some examples?
Edit: By looking in your 7DTD.dll Cheat.Globals i see LocalPlayer is refrenced to game one but i don't see any Assembly-CsHarp.dll refrecen and dll was not injected yet... 
I'm new and want to know how is this made

**Comment by IntelSDM** [comment]
You must manually hijack an assembly by referencing the cheat's loader. The LocalPlayer is a variable name as an instance of a player.
