### ISSUE TITLE
Menu hotkeys

### ISSUE THREAD

**Issue by TheSolaire** [IntelSDM/7DTD#21]
Followed the instructions and the main cheat menu appears but I am not sure how to go back menus. If you go into the settings of something specific like the aimbot then if you press the backwards key it doesn't take you to the previous menu and insert just makes the menu dissappear.

Any help is deeply appreciated, thanks for your amazing project!

**Comment by IntelSDM** [comment]
Insert to open and close it. Arrow keys to navigate up and down and increase/ decrease values. Enter to open a menu, Subtract to go back a menu
