### ISSUE TITLE
Remove negative buffs

### ISSUE THREAD

**Issue by mbNightstalker** [IntelSDM/7DTD#9]
I have noticed you have a manual list of negative buffs. 
How about replacing it with this? It does exactly the same without having maintain a buff list.
It's exactly what "RemoveAllNegativeBuffs" does with low level players when they respawn.

```cs
public static void RemoveAllNegativeBuffs()
{
    EntityPlayer primaryPlayer = GameManager.Instance.World.GetPrimaryPlayer();
    for (int index = 0; index < primaryPlayer.Buffs.ActiveBuffs.Count; ++index)
    {
        if (primaryPlayer.Buffs.ActiveBuffs[index].BuffClass.DamageType != EnumDamageTypes.None)
            primaryPlayer.Buffs.ActiveBuffs[index].Remove = true;
    }
}
```

**Comment by IntelSDM** [comment]
Thanks for the feature improvement. I will add it later on today.

**Comment by IntelSDM** [comment]
I have been busy so this was delayed. I have added the feature now.
